### ISSUE TITLE
handler._setRouteName is not a function

### ISSUE THREAD

**Issue by fpalluel** [knownasilya/ember-admin-demo#1]
Hello,
I just gave a try to the demo, and I'm facing this error.
Even if I force the ember version from 2.10.beta to 2.9.1, the error still appears...

Am I overlooking anything ?
Thanks !

**Comment by knownasilya** [comment]
2.10 isn't a beta, give 2.10.2 a try.

**Comment by fpalluel** [comment]
It was beta, back in december ;-)
I just gave it a try and it seems to work, thanks.
